CREATE TABLE categoria_produto( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE clientes( 
      id  integer generated by default as identity     NOT NULL , 
      nome varchar  (30)   , 
      email varchar  (50)   , 
      telefone varchar  (50)   , 
      endereco varchar  (50)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE itens_vendas( 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (50)   , 
      quantidade integer  (50)   , 
      preco_unitario integer  (50)   , 
      preco_total integer  (50)   , 
      vendas_id integer    NOT NULL , 
      produto_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE movimentacao( 
      id  integer generated by default as identity     NOT NULL , 
      produto_id integer    NOT NULL , 
      quantidade integer   , 
      data_movimentacao timestamp   , 
      tipo_movimentacao_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE produto( 
      id  integer generated by default as identity     NOT NULL , 
      categoria_produto_id integer    NOT NULL , 
      nome blob sub_type 1   , 
      total_estoque integer   , 
      valor float   , 
      imagem blob sub_type 1   , 
      valor_atacado float  (20)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_movimentacao( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE vendas( 
      id  integer generated by default as identity     NOT NULL , 
      data_venda timestamp   , 
      produto_id integer    NOT NULL , 
      total_venda integer   , 
      forma_pagamento char  (50)   , 
      vendedor blob sub_type 1   , 
      lucro integer   , 
      faturamento integer   , 
      valor float   , 
      nome_produto blob sub_type 1   , 
      quantidade integer  (30)   , 
      clientes_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

 
  
 ALTER TABLE itens_vendas ADD CONSTRAINT fk_itens_vendas_1 FOREIGN KEY (vendas_id) references vendas(id); 
ALTER TABLE itens_vendas ADD CONSTRAINT fk_itens_vendas_2 FOREIGN KEY (produto_id) references produto(id); 
ALTER TABLE movimentacao ADD CONSTRAINT fk_movimentacao_1 FOREIGN KEY (produto_id) references produto(id); 
ALTER TABLE movimentacao ADD CONSTRAINT fk_movimentacao_2 FOREIGN KEY (tipo_movimentacao_id) references tipo_movimentacao(id); 
ALTER TABLE produto ADD CONSTRAINT fk_produto_1 FOREIGN KEY (categoria_produto_id) references categoria_produto(id); 
ALTER TABLE vendas ADD CONSTRAINT fk_vendas_1 FOREIGN KEY (produto_id) references produto(id); 
ALTER TABLE vendas ADD CONSTRAINT fk_vendas_2 FOREIGN KEY (clientes_id) references clientes(id); 
